addSbtPlugin("org.scala-js"           % "sbt-scalajs"                   % "1.12.0")
addSbtPlugin("org.portable-scala"     % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("org.scala-native"       % "sbt-scala-native"              % "0.4.9")
addSbtPlugin("org.portable-scala"     % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-lang.modules" % "sbt-scala-module"              % "3.0.1")
addSbtPlugin("ch.epfl.scala"          % "sbt-scalafix"                  % "0.10.4")
addSbtPlugin("com.eed3si9n"           % "sbt-buildinfo"                 % "0.11.0")
